import { NextApiRequest, NextApiResponse } from 'next';

/**
 * During development you can use this API to avoid hitting the proper API all the time. Only contains a small subset of the data.
 */
export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (process.env.NODE_ENV === 'production') {
    throw new Error('Mock route accessed in production!');
  }
  res.status(200).json([
    {
      name: {
        common: 'Saudi Arabia',
        official: 'Kingdom of Saudi Arabia',
        nativeName: {
          ara: {
            official: 'المملكة العربية السعودية',
            common: 'العربية السعودية',
          },
        },
      },
      tld: ['.sa', '.السعودية'],
      cca2: 'SA',
      ccn3: '682',
      cca3: 'SAU',
      cioc: 'KSA',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { SAR: { name: 'Saudi riyal', symbol: 'ر.س' } },
      idd: { root: '+9', suffixes: ['66'] },
      capital: ['Riyadh'],
      altSpellings: ['Saudi', 'SA', 'Kingdom of Saudi Arabia', 'Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah'],
      region: 'Asia',
      subregion: 'Western Asia',
      languages: { ara: 'Arabic' },
      translations: {
        ara: { official: 'المملكة العربية السعودية', common: 'السعودية' },
        bre: {
          official: 'Rouantelezh Arabia Saoudat',
          common: 'Arabia Saoudat',
        },
        ces: {
          official: 'Saúdskoarabské království',
          common: 'Saúdská Arábie',
        },
        cym: {
          official: 'Kingdom of Saudi Arabia',
          common: 'Saudi Arabia',
        },
        deu: {
          official: 'Königreich Saudi-Arabien',
          common: 'Saudi-Arabien',
        },
        est: {
          official: 'Saudi Araabia Kuningriik',
          common: 'Saudi Araabia',
        },
        fin: {
          official: 'Saudi-Arabian kuningaskunta',
          common: 'Saudi-Arabia',
        },
        fra: {
          official: "Royaume d'Arabie Saoudite",
          common: 'Arabie Saoudite',
        },
        hrv: {
          official: 'Kraljevina Saudijska Arabija',
          common: 'Saudijska Arabija',
        },
        hun: { official: 'Szaúd-Arábia', common: 'Szaúd-Arábia' },
        ita: { official: 'Arabia Saudita', common: 'Arabia Saudita' },
        jpn: { official: 'サウジアラビア王国', common: 'サウジアラビア' },
        kor: { official: '사우디아라비아 왕국', common: '사우디아라비아' },
        nld: {
          official: 'Koninkrijk van Saoedi-Arabië',
          common: 'Saoedi-Arabië',
        },
        per: { official: 'پادشاهی عربی سَعودی', common: 'عربستان سعودی' },
        pol: {
          official: 'Królestwo Arabii Saudyjskiej',
          common: 'Arabia Saudyjska',
        },
        por: {
          official: 'Reino da Arábia Saudita',
          common: 'Arábia Saudita',
        },
        rus: {
          official: 'Королевство Саудовская Аравия',
          common: 'Саудовская Аравия',
        },
        slk: {
          official: 'Saudskoarabské kráľovstvo',
          common: 'Saudská Arábia',
        },
        spa: {
          official: 'Reino de Arabia Saudita',
          common: 'Arabia Saudí',
        },
        srp: {
          official: 'Краљевина Саудијска Арабија',
          common: 'Саудијска Арабија',
        },
        swe: {
          official: 'Kungadömet Saudiarabien',
          common: 'Saudiarabien',
        },
        tur: {
          official: 'Suudi Arabistan Krallığı',
          common: 'Suudi Arabistan',
        },
        urd: { official: 'مملکتِ سعودی عرب', common: 'سعودی عرب' },
        zho: { official: '沙特阿拉伯王国', common: '沙特阿拉伯' },
      },
      latlng: [25.0, 45.0],
      landlocked: false,
      borders: ['IRQ', 'JOR', 'KWT', 'OMN', 'QAT', 'ARE', 'YEM'],
      area: 2149690.0,
      demonyms: {
        eng: { f: 'Saudi Arabian', m: 'Saudi Arabian' },
        fra: { f: 'Saoudienne', m: 'Saoudien' },
      },
      flag: '\uD83C\uDDF8\uD83C\uDDE6',
      maps: {
        googleMaps: 'https://goo.gl/maps/5PSjvdJ1AyaLFRrG9',
        openStreetMaps: 'https://www.openstreetmap.org/relation/307584',
      },
      population: 34813867,
      fifa: 'KSA',
      car: { signs: ['SA'], side: 'right' },
      timezones: ['UTC+03:00'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/sa.png',
        svg: 'https://flagcdn.com/sa.svg',
        alt: 'The flag of Saudi Arabia has a green field, at the center of which is an Arabic inscription — the Shahada — in white above a white horizontal sabre with its tip pointed to the hoist side of the field.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/sa.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/sa.svg',
      },
      startOfWeek: 'sunday',
      capitalInfo: { latlng: [24.65, 46.7] },
      postalCode: { format: '#####', regex: '^(\\d{5})$' },
    },
    {
      name: {
        common: 'Cameroon',
        official: 'Republic of Cameroon',
        nativeName: {
          eng: { official: 'Republic of Cameroon', common: 'Cameroon' },
          fra: { official: 'République du Cameroun', common: 'Cameroun' },
        },
      },
      tld: ['.cm'],
      cca2: 'CM',
      ccn3: '120',
      cca3: 'CMR',
      cioc: 'CMR',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: {
        XAF: { name: 'Central African CFA franc', symbol: 'Fr' },
      },
      idd: { root: '+2', suffixes: ['37'] },
      capital: ['Yaoundé'],
      altSpellings: ['CM', 'Republic of Cameroon', 'République du Cameroun'],
      region: 'Africa',
      subregion: 'Middle Africa',
      languages: { eng: 'English', fra: 'French' },
      translations: {
        ara: { official: 'جمهورية الكاميرون', common: 'الكاميرون' },
        bre: { official: 'Republik Kameroun', common: 'Kameroun' },
        ces: { official: 'Kamerunská republika', common: 'Kamerun' },
        cym: { official: 'Gweriniaeth Camerŵn', common: 'Camerŵn' },
        deu: { official: 'Republik Kamerun', common: 'Kamerun' },
        est: { official: 'Kameruni Vabariik', common: 'Kamerun' },
        fin: { official: 'Kamerunin tasavalta', common: 'Kamerun' },
        fra: { official: 'République du Cameroun', common: 'Cameroun' },
        hrv: { official: 'Republika Kamerun', common: 'Kamerun' },
        hun: { official: 'Kameruni Köztársaság', common: 'Kamerun' },
        ita: { official: 'Repubblica del Camerun', common: 'Camerun' },
        jpn: { official: 'カメルーン共和国', common: 'カメルーン' },
        kor: { official: '카메룬 공화국', common: '카메룬' },
        nld: { official: 'Republiek Kameroen', common: 'Kameroen' },
        per: { official: 'جمهوری کامِرون', common: 'کامِرون' },
        pol: { official: 'Republika Kamerunu', common: 'Kamerun' },
        por: { official: 'República dos Camarões', common: 'Camarões' },
        rus: { official: 'Республика Камерун', common: 'Камерун' },
        slk: { official: 'Kamerunská republika', common: 'Kamerun' },
        spa: { official: 'República de Camerún', common: 'Camerún' },
        srp: { official: 'Република Камерун', common: 'Камерун' },
        swe: { official: 'Republiken Kamerun', common: 'Kamerun' },
        tur: { official: 'Kamerun Cumhuriyeti', common: 'Kamerun' },
        urd: { official: 'جمہوریہ کیمرون', common: 'کیمرون' },
        zho: { official: '喀麦隆共和国', common: '喀麦隆' },
      },
      latlng: [6.0, 12.0],
      landlocked: false,
      borders: ['CAF', 'TCD', 'COG', 'GNQ', 'GAB', 'NGA'],
      area: 475442.0,
      demonyms: {
        eng: { f: 'Cameroonian', m: 'Cameroonian' },
        fra: { f: 'Camerounaise', m: 'Camerounais' },
      },
      flag: '\uD83C\uDDE8\uD83C\uDDF2',
      maps: {
        googleMaps: 'https://goo.gl/maps/JqiipHgFboG3rBJh9',
        openStreetMaps: 'https://www.openstreetmap.org/relation/192830',
      },
      population: 26545864,
      gini: { '2014': 46.6 },
      fifa: 'CMR',
      car: { signs: ['CAM'], side: 'right' },
      timezones: ['UTC+01:00'],
      continents: ['Africa'],
      flags: {
        png: 'https://flagcdn.com/w320/cm.png',
        svg: 'https://flagcdn.com/cm.svg',
        alt: 'The flag of Cameroon is composed of three equal vertical bands of green, red and yellow, with a yellow five-pointed star in the center.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/cm.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/cm.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [3.85, 11.5] },
    },
    {
      name: {
        common: 'Iran',
        official: 'Islamic Republic of Iran',
        nativeName: {
          fas: { official: 'جمهوری اسلامی ایران', common: 'ایران' },
        },
      },
      tld: ['.ir', 'ایران.'],
      cca2: 'IR',
      ccn3: '364',
      cca3: 'IRN',
      cioc: 'IRI',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { IRR: { name: 'Iranian rial', symbol: '﷼' } },
      idd: { root: '+9', suffixes: ['8'] },
      capital: ['Tehran'],
      altSpellings: ['IR', 'Islamic Republic of Iran', 'Iran, Islamic Republic of', 'Jomhuri-ye Eslāmi-ye Irān'],
      region: 'Asia',
      subregion: 'Southern Asia',
      languages: { fas: 'Persian (Farsi)' },
      translations: {
        ara: { official: 'جمهورية إيران الإسلامية', common: 'إيران' },
        bre: { official: 'Republik Islamek Iran', common: 'Iran' },
        ces: { official: 'Islámská republika Írán', common: 'Írán' },
        cym: { official: 'Islamic Republic of Iran', common: 'Iran' },
        deu: { official: 'Islamische Republik Iran', common: 'Iran' },
        est: { official: 'Iraani Islamivabariik', common: 'Iraan' },
        fin: { official: 'Iranin islamilainen tasavalta', common: 'Iran' },
        fra: { official: "République islamique d'Iran", common: 'Iran' },
        hrv: { official: 'Islamska Republika Iran', common: 'Iran' },
        hun: { official: 'Iráni Iszlám Köztársaság', common: 'Irán' },
        ita: { official: "Repubblica islamica dell'Iran", common: 'Iran' },
        jpn: {
          official: 'イラン·イスラム共和国',
          common: 'イラン・イスラム共和国',
        },
        kor: { official: '이란 이슬람 공화국', common: '이란' },
        nld: { official: 'Islamitische Republiek Iran', common: 'Iran' },
        pol: { official: 'Islamska Republika Iranu', common: 'Iran' },
        por: { official: 'República Islâmica do Irã', common: 'Irão' },
        rus: { official: 'Исламская Республика Иран', common: 'Иран' },
        slk: { official: 'Iránska islamská republika', common: 'Irán' },
        spa: { official: 'República Islámica de Irán', common: 'Iran' },
        srp: { official: 'Исламска Република Иран', common: 'Иран' },
        swe: { official: 'Islamiska republiken Iran', common: 'Iran' },
        tur: { official: 'İran İslam Cumhuriyeti', common: 'İran' },
        urd: { official: 'جمہوریہ ایران', common: 'ایران' },
        zho: { official: '伊朗伊斯兰共和国', common: '伊朗' },
      },
      latlng: [32.0, 53.0],
      landlocked: false,
      borders: ['AFG', 'ARM', 'AZE', 'IRQ', 'PAK', 'TUR', 'TKM'],
      area: 1648195.0,
      demonyms: {
        eng: { f: 'Iranian', m: 'Iranian' },
        fra: { f: 'Iranienne', m: 'Iranien' },
      },
      flag: '\uD83C\uDDEE\uD83C\uDDF7',
      maps: {
        googleMaps: 'https://goo.gl/maps/dMgEGuacBPGYQnjY7',
        openStreetMaps: 'https://www.openstreetmap.org/relation/304938',
      },
      population: 83992953,
      gini: { '2018': 42.0 },
      fifa: 'IRN',
      car: { signs: ['IR'], side: 'right' },
      timezones: ['UTC+03:30'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/ir.png',
        svg: 'https://flagcdn.com/ir.svg',
        alt: 'The flag of Iran is composed of three equal horizontal bands of green, white and red. A red emblem of Iran is centered in the white band and Arabic inscriptions in white span the bottom edge of the green band and the top edge of the red band.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ir.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ir.svg',
      },
      startOfWeek: 'saturday',
      capitalInfo: { latlng: [35.7, 51.42] },
      postalCode: { format: '##########', regex: '^(\\d{10})$' },
    },
    {
      name: {
        common: 'United Arab Emirates',
        official: 'United Arab Emirates',
        nativeName: {
          ara: {
            official: 'الإمارات العربية المتحدة',
            common: 'دولة الإمارات العربية المتحدة',
          },
        },
      },
      tld: ['.ae', 'امارات.'],
      cca2: 'AE',
      ccn3: '784',
      cca3: 'ARE',
      cioc: 'UAE',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: {
        AED: { name: 'United Arab Emirates dirham', symbol: 'د.إ' },
      },
      idd: { root: '+9', suffixes: ['71'] },
      capital: ['Abu Dhabi'],
      altSpellings: ['AE', 'UAE', 'Emirates'],
      region: 'Asia',
      subregion: 'Western Asia',
      languages: { ara: 'Arabic' },
      translations: {
        ara: {
          official: 'الإمارات العربية المتحدة',
          common: 'دولة الإمارات العربية المتحدة',
        },
        bre: {
          official: 'Emirelezhioù Arab Unanet',
          common: 'Emirelezhioù Arab Unanet',
        },
        ces: {
          official: 'Spojené arabské emiráty',
          common: 'Arabské emiráty',
        },
        cym: {
          official: 'United Arab Emirates',
          common: 'United Arab Emirates',
        },
        deu: {
          official: 'Vereinigte Arabische Emirate',
          common: 'Vereinigte Arabische Emirate',
        },
        est: {
          official: 'Araabia Ühendemiraadid',
          common: 'Araabia Ühendemiraadid',
        },
        fin: {
          official: 'Yhdistyneet arabiemiirikunnat',
          common: 'Arabiemiraatit',
        },
        fra: {
          official: 'Émirats arabes unis',
          common: 'Émirats arabes unis',
        },
        hrv: {
          official: 'Ujedinjeni Arapski Emirati',
          common: 'Arapski Emirati',
        },
        hun: {
          official: 'Egyesült Arab Emírségek',
          common: 'Egyesült Arab Emírségek',
        },
        ita: {
          official: 'Emirati Arabi Uniti',
          common: 'Emirati Arabi Uniti',
        },
        jpn: { official: 'アラブ首長国連邦', common: 'アラブ首長国連邦' },
        kor: { official: '아랍 토후국 연방', common: '아랍에미리트' },
        nld: {
          official: 'Verenigde Arabische Emiraten',
          common: 'Verenigde Arabische Emiraten',
        },
        per: { official: 'امارات متحده عربی', common: 'امارات' },
        pol: {
          official: 'Zjednoczone Emiraty Arabskie',
          common: 'Emiraty Arabskie',
        },
        por: {
          official: 'Emirados Árabes Unidos',
          common: 'Emirados Árabes Unidos',
        },
        rus: {
          official: 'Объединенные Арабские Эмираты',
          common: 'Объединённые Арабские Эмираты',
        },
        slk: {
          official: 'Spojené arabské emiráty',
          common: 'Arabské emiráty',
        },
        spa: {
          official: 'Emiratos Árabes Unidos',
          common: 'Emiratos Árabes Unidos',
        },
        srp: {
          official: 'Уједињени Арапски Емирати',
          common: 'Уједињени Арапски Емирати',
        },
        swe: {
          official: 'Förenade Arabemiraten',
          common: 'Förenade Arabemiraten',
        },
        tur: {
          official: 'Birleşik Arap Emirlikleri',
          common: 'Birleşik Arap Emirlikleri',
        },
        urd: { official: 'متحدہ عرب امارات', common: 'متحدہ عرب امارات' },
        zho: { official: '阿拉伯联合酋长国', common: '阿拉伯联合酋长国' },
      },
      latlng: [24.0, 54.0],
      landlocked: false,
      borders: ['OMN', 'SAU'],
      area: 83600.0,
      demonyms: {
        eng: { f: 'Emirati', m: 'Emirati' },
        fra: { f: 'Emirienne', m: 'Emirien' },
      },
      flag: '\uD83C\uDDE6\uD83C\uDDEA',
      maps: {
        googleMaps: 'https://goo.gl/maps/AZZTDA6GzVAnKMVd8',
        openStreetMaps: 'https://www.openstreetmap.org/relation/307763',
      },
      population: 9890400,
      gini: { '2018': 26.0 },
      fifa: 'UAE',
      car: { signs: ['UAE'], side: 'right' },
      timezones: ['UTC+04:00'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/ae.png',
        svg: 'https://flagcdn.com/ae.svg',
        alt: 'The flag of United Arab Emirates features a red vertical band on its hoist side that takes up about one-fourth the width of the field and three equal horizontal bands of green, white and black adjoining the vertical band.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ae.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ae.svg',
      },
      startOfWeek: 'sunday',
      capitalInfo: { latlng: [24.47, 54.37] },
    },
    {
      name: {
        common: 'Ukraine',
        official: 'Ukraine',
        nativeName: { ukr: { official: 'Україна', common: 'Україна' } },
      },
      tld: ['.ua', '.укр'],
      cca2: 'UA',
      ccn3: '804',
      cca3: 'UKR',
      cioc: 'UKR',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { UAH: { name: 'Ukrainian hryvnia', symbol: '₴' } },
      idd: { root: '+3', suffixes: ['80'] },
      capital: ['Kyiv'],
      altSpellings: ['UA', 'Ukrayina'],
      region: 'Europe',
      subregion: 'Eastern Europe',
      languages: { ukr: 'Ukrainian' },
      translations: {
        ara: { official: 'أوكرانيا', common: 'أوكرانيا' },
        bre: { official: 'Ukraina', common: 'Ukraina' },
        ces: { official: 'Ukrajina', common: 'Ukrajina' },
        cym: { official: 'Ukraine', common: 'Ukraine' },
        deu: { official: 'Ukraine', common: 'Ukraine' },
        est: { official: 'Ukraina', common: 'Ukraina' },
        fin: { official: 'Ukraina', common: 'Ukraina' },
        fra: { official: 'Ukraine', common: 'Ukraine' },
        hrv: { official: 'Ukrajina', common: 'Ukrajina' },
        hun: { official: 'Ukrajna', common: 'Ukrajna' },
        ita: { official: 'Ucraina', common: 'Ucraina' },
        jpn: { official: 'ウクライナ', common: 'ウクライナ' },
        kor: { official: '우크라이나', common: '우크라이나' },
        nld: { official: 'Oekraïne', common: 'Oekraïne' },
        per: { official: 'اوکراین', common: 'اوکراین' },
        pol: { official: 'Ukraina', common: 'Ukraina' },
        por: { official: 'Ucrânia', common: 'Ucrânia' },
        rus: { official: 'Украина', common: 'Украина' },
        slk: { official: 'Ukrajina', common: 'Ukrajina' },
        spa: { official: 'Ucrania', common: 'Ucrania' },
        srp: { official: 'Украјина', common: 'Украјина' },
        swe: { official: 'Ukraina', common: 'Ukraina' },
        tur: { official: 'Ukrayna', common: 'Ukrayna' },
        urd: { official: 'یوکرین', common: 'یوکرین' },
        zho: { official: '乌克兰', common: '乌克兰' },
      },
      latlng: [49.0, 32.0],
      landlocked: false,
      borders: ['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK'],
      area: 603500.0,
      demonyms: {
        eng: { f: 'Ukrainian', m: 'Ukrainian' },
        fra: { f: 'Ukrainienne', m: 'Ukrainien' },
      },
      flag: '\uD83C\uDDFA\uD83C\uDDE6',
      maps: {
        googleMaps: 'https://goo.gl/maps/DvgJMiPJ7aozKFZv7',
        openStreetMaps: 'https://www.openstreetmap.org/relation/60199',
      },
      population: 44134693,
      gini: { '2019': 26.6 },
      fifa: 'UKR',
      car: { signs: ['UA'], side: 'right' },
      timezones: ['UTC+02:00'],
      continents: ['Europe'],
      flags: {
        png: 'https://flagcdn.com/w320/ua.png',
        svg: 'https://flagcdn.com/ua.svg',
        alt: 'The flag of Ukraine is composed of two equal horizontal bands of blue and yellow.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ua.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ua.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [50.43, 30.52] },
      postalCode: { format: '#####', regex: '^(\\d{5})$' },
    },
  ]);
}
