import { NextApiRequest, NextApiResponse } from 'next';

/**
 * During development you can use this API to avoid hitting the proper API all the time. Only contains a small subset of the data.
 */
export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (process.env.NODE_ENV === 'production') {
    throw new Error('Mock route accessed in production!');
  }
  res.status(200).json([
    {
      name: {
        common: 'Saudi Arabia',
        official: 'Kingdom of Saudi Arabia',
        nativeName: {
          ara: {
            official: 'المملكة العربية السعودية',
            common: 'العربية السعودية',
          },
        },
      },
      tld: ['.sa', '.السعودية'],
      cca2: 'SA',
      ccn3: '682',
      cca3: 'SAU',
      cioc: 'KSA',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { SAR: { name: 'Saudi riyal', symbol: 'ر.س' } },
      idd: { root: '+9', suffixes: ['66'] },
      capital: ['Riyadh'],
      altSpellings: ['Saudi', 'SA', 'Kingdom of Saudi Arabia', 'Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah'],
      region: 'Asia',
      subregion: 'Western Asia',
      languages: { ara: 'Arabic' },
      translations: {
        ara: { official: 'المملكة العربية السعودية', common: 'السعودية' },
        bre: {
          official: 'Rouantelezh Arabia Saoudat',
          common: 'Arabia Saoudat',
        },
        ces: {
          official: 'Saúdskoarabské království',
          common: 'Saúdská Arábie',
        },
        cym: {
          official: 'Kingdom of Saudi Arabia',
          common: 'Saudi Arabia',
        },
        deu: {
          official: 'Königreich Saudi-Arabien',
          common: 'Saudi-Arabien',
        },
        est: {
          official: 'Saudi Araabia Kuningriik',
          common: 'Saudi Araabia',
        },
        fin: {
          official: 'Saudi-Arabian kuningaskunta',
          common: 'Saudi-Arabia',
        },
        fra: {
          official: "Royaume d'Arabie Saoudite",
          common: 'Arabie Saoudite',
        },
        hrv: {
          official: 'Kraljevina Saudijska Arabija',
          common: 'Saudijska Arabija',
        },
        hun: { official: 'Szaúd-Arábia', common: 'Szaúd-Arábia' },
        ita: { official: 'Arabia Saudita', common: 'Arabia Saudita' },
        jpn: { official: 'サウジアラビア王国', common: 'サウジアラビア' },
        kor: { official: '사우디아라비아 왕국', common: '사우디아라비아' },
        nld: {
          official: 'Koninkrijk van Saoedi-Arabië',
          common: 'Saoedi-Arabië',
        },
        per: { official: 'پادشاهی عربی سَعودی', common: 'عربستان سعودی' },
        pol: {
          official: 'Królestwo Arabii Saudyjskiej',
          common: 'Arabia Saudyjska',
        },
        por: {
          official: 'Reino da Arábia Saudita',
          common: 'Arábia Saudita',
        },
        rus: {
          official: 'Королевство Саудовская Аравия',
          common: 'Саудовская Аравия',
        },
        slk: {
          official: 'Saudskoarabské kráľovstvo',
          common: 'Saudská Arábia',
        },
        spa: {
          official: 'Reino de Arabia Saudita',
          common: 'Arabia Saudí',
        },
        srp: {
          official: 'Краљевина Саудијска Арабија',
          common: 'Саудијска Арабија',
        },
        swe: {
          official: 'Kungadömet Saudiarabien',
          common: 'Saudiarabien',
        },
        tur: {
          official: 'Suudi Arabistan Krallığı',
          common: 'Suudi Arabistan',
        },
        urd: { official: 'مملکتِ سعودی عرب', common: 'سعودی عرب' },
        zho: { official: '沙特阿拉伯王国', common: '沙特阿拉伯' },
      },
      latlng: [25.0, 45.0],
      landlocked: false,
      borders: ['IRQ', 'JOR', 'KWT', 'OMN', 'QAT', 'ARE', 'YEM'],
      area: 2149690.0,
      demonyms: {
        eng: { f: 'Saudi Arabian', m: 'Saudi Arabian' },
        fra: { f: 'Saoudienne', m: 'Saoudien' },
      },
      flag: '\uD83C\uDDF8\uD83C\uDDE6',
      maps: {
        googleMaps: 'https://goo.gl/maps/5PSjvdJ1AyaLFRrG9',
        openStreetMaps: 'https://www.openstreetmap.org/relation/307584',
      },
      population: 34813867,
      fifa: 'KSA',
      car: { signs: ['SA'], side: 'right' },
      timezones: ['UTC+03:00'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/sa.png',
        svg: 'https://flagcdn.com/sa.svg',
        alt: 'The flag of Saudi Arabia has a green field, at the center of which is an Arabic inscription — the Shahada — in white above a white horizontal sabre with its tip pointed to the hoist side of the field.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/sa.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/sa.svg',
      },
      startOfWeek: 'sunday',
      capitalInfo: { latlng: [24.65, 46.7] },
      postalCode: { format: '#####', regex: '^(\\d{5})$' },
    },
    {
      name: {
        common: 'Cameroon',
        official: 'Republic of Cameroon',
        nativeName: {
          eng: { official: 'Republic of Cameroon', common: 'Cameroon' },
          fra: { official: 'République du Cameroun', common: 'Cameroun' },
        },
      },
      tld: ['.cm'],
      cca2: 'CM',
      ccn3: '120',
      cca3: 'CMR',
      cioc: 'CMR',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: {
        XAF: { name: 'Central African CFA franc', symbol: 'Fr' },
      },
      idd: { root: '+2', suffixes: ['37'] },
      capital: ['Yaoundé'],
      altSpellings: ['CM', 'Republic of Cameroon', 'République du Cameroun'],
      region: 'Africa',
      subregion: 'Middle Africa',
      languages: { eng: 'English', fra: 'French' },
      translations: {
        ara: { official: 'جمهورية الكاميرون', common: 'الكاميرون' },
        bre: { official: 'Republik Kameroun', common: 'Kameroun' },
        ces: { official: 'Kamerunská republika', common: 'Kamerun' },
        cym: { official: 'Gweriniaeth Camerŵn', common: 'Camerŵn' },
        deu: { official: 'Republik Kamerun', common: 'Kamerun' },
        est: { official: 'Kameruni Vabariik', common: 'Kamerun' },
        fin: { official: 'Kamerunin tasavalta', common: 'Kamerun' },
        fra: { official: 'République du Cameroun', common: 'Cameroun' },
        hrv: { official: 'Republika Kamerun', common: 'Kamerun' },
        hun: { official: 'Kameruni Köztársaság', common: 'Kamerun' },
        ita: { official: 'Repubblica del Camerun', common: 'Camerun' },
        jpn: { official: 'カメルーン共和国', common: 'カメルーン' },
        kor: { official: '카메룬 공화국', common: '카메룬' },
        nld: { official: 'Republiek Kameroen', common: 'Kameroen' },
        per: { official: 'جمهوری کامِرون', common: 'کامِرون' },
        pol: { official: 'Republika Kamerunu', common: 'Kamerun' },
        por: { official: 'República dos Camarões', common: 'Camarões' },
        rus: { official: 'Республика Камерун', common: 'Камерун' },
        slk: { official: 'Kamerunská republika', common: 'Kamerun' },
        spa: { official: 'República de Camerún', common: 'Camerún' },
        srp: { official: 'Република Камерун', common: 'Камерун' },
        swe: { official: 'Republiken Kamerun', common: 'Kamerun' },
        tur: { official: 'Kamerun Cumhuriyeti', common: 'Kamerun' },
        urd: { official: 'جمہوریہ کیمرون', common: 'کیمرون' },
        zho: { official: '喀麦隆共和国', common: '喀麦隆' },
      },
      latlng: [6.0, 12.0],
      landlocked: false,
      borders: ['CAF', 'TCD', 'COG', 'GNQ', 'GAB', 'NGA'],
      area: 475442.0,
      demonyms: {
        eng: { f: 'Cameroonian', m: 'Cameroonian' },
        fra: { f: 'Camerounaise', m: 'Camerounais' },
      },
      flag: '\uD83C\uDDE8\uD83C\uDDF2',
      maps: {
        googleMaps: 'https://goo.gl/maps/JqiipHgFboG3rBJh9',
        openStreetMaps: 'https://www.openstreetmap.org/relation/192830',
      },
      population: 26545864,
      gini: { '2014': 46.6 },
      fifa: 'CMR',
      car: { signs: ['CAM'], side: 'right' },
      timezones: ['UTC+01:00'],
      continents: ['Africa'],
      flags: {
        png: 'https://flagcdn.com/w320/cm.png',
        svg: 'https://flagcdn.com/cm.svg',
        alt: 'The flag of Cameroon is composed of three equal vertical bands of green, red and yellow, with a yellow five-pointed star in the center.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/cm.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/cm.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [3.85, 11.5] },
    },
    {
      name: {
        common: 'Iran',
        official: 'Islamic Republic of Iran',
        nativeName: {
          fas: { official: 'جمهوری اسلامی ایران', common: 'ایران' },
        },
      },
      tld: ['.ir', 'ایران.'],
      cca2: 'IR',
      ccn3: '364',
      cca3: 'IRN',
      cioc: 'IRI',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { IRR: { name: 'Iranian rial', symbol: '﷼' } },
      idd: { root: '+9', suffixes: ['8'] },
      capital: ['Tehran'],
      altSpellings: ['IR', 'Islamic Republic of Iran', 'Iran, Islamic Republic of', 'Jomhuri-ye Eslāmi-ye Irān'],
      region: 'Asia',
      subregion: 'Southern Asia',
      languages: { fas: 'Persian (Farsi)' },
      translations: {
        ara: { official: 'جمهورية إيران الإسلامية', common: 'إيران' },
        bre: { official: 'Republik Islamek Iran', common: 'Iran' },
        ces: { official: 'Islámská republika Írán', common: 'Írán' },
        cym: { official: 'Islamic Republic of Iran', common: 'Iran' },
        deu: { official: 'Islamische Republik Iran', common: 'Iran' },
        est: { official: 'Iraani Islamivabariik', common: 'Iraan' },
        fin: { official: 'Iranin islamilainen tasavalta', common: 'Iran' },
        fra: { official: "République islamique d'Iran", common: 'Iran' },
        hrv: { official: 'Islamska Republika Iran', common: 'Iran' },
        hun: { official: 'Iráni Iszlám Köztársaság', common: 'Irán' },
        ita: { official: "Repubblica islamica dell'Iran", common: 'Iran' },
        jpn: {
          official: 'イラン·イスラム共和国',
          common: 'イラン・イスラム共和国',
        },
        kor: { official: '이란 이슬람 공화국', common: '이란' },
        nld: { official: 'Islamitische Republiek Iran', common: 'Iran' },
        pol: { official: 'Islamska Republika Iranu', common: 'Iran' },
        por: { official: 'República Islâmica do Irã', common: 'Irão' },
        rus: { official: 'Исламская Республика Иран', common: 'Иран' },
        slk: { official: 'Iránska islamská republika', common: 'Irán' },
        spa: { official: 'República Islámica de Irán', common: 'Iran' },
        srp: { official: 'Исламска Република Иран', common: 'Иран' },
        swe: { official: 'Islamiska republiken Iran', common: 'Iran' },
        tur: { official: 'İran İslam Cumhuriyeti', common: 'İran' },
        urd: { official: 'جمہوریہ ایران', common: 'ایران' },
        zho: { official: '伊朗伊斯兰共和国', common: '伊朗' },
      },
      latlng: [32.0, 53.0],
      landlocked: false,
      borders: ['AFG', 'ARM', 'AZE', 'IRQ', 'PAK', 'TUR', 'TKM'],
      area: 1648195.0,
      demonyms: {
        eng: { f: 'Iranian', m: 'Iranian' },
        fra: { f: 'Iranienne', m: 'Iranien' },
      },
      flag: '\uD83C\uDDEE\uD83C\uDDF7',
      maps: {
        googleMaps: 'https://goo.gl/maps/dMgEGuacBPGYQnjY7',
        openStreetMaps: 'https://www.openstreetmap.org/relation/304938',
      },
      population: 83992953,
      gini: { '2018': 42.0 },
      fifa: 'IRN',
      car: { signs: ['IR'], side: 'right' },
      timezones: ['UTC+03:30'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/ir.png',
        svg: 'https://flagcdn.com/ir.svg',
        alt: 'The flag of Iran is composed of three equal horizontal bands of green, white and red. A red emblem of Iran is centered in the white band and Arabic inscriptions in white span the bottom edge of the green band and the top edge of the red band.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ir.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ir.svg',
      },
      startOfWeek: 'saturday',
      capitalInfo: { latlng: [35.7, 51.42] },
      postalCode: { format: '##########', regex: '^(\\d{10})$' },
    },
    {
      name: {
        common: 'United Arab Emirates',
        official: 'United Arab Emirates',
        nativeName: {
          ara: {
            official: 'الإمارات العربية المتحدة',
            common: 'دولة الإمارات العربية المتحدة',
          },
        },
      },
      tld: ['.ae', 'امارات.'],
      cca2: 'AE',
      ccn3: '784',
      cca3: 'ARE',
      cioc: 'UAE',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: {
        AED: { name: 'United Arab Emirates dirham', symbol: 'د.إ' },
      },
      idd: { root: '+9', suffixes: ['71'] },
      capital: ['Abu Dhabi'],
      altSpellings: ['AE', 'UAE', 'Emirates'],
      region: 'Asia',
      subregion: 'Western Asia',
      languages: { ara: 'Arabic' },
      translations: {
        ara: {
          official: 'الإمارات العربية المتحدة',
          common: 'دولة الإمارات العربية المتحدة',
        },
        bre: {
          official: 'Emirelezhioù Arab Unanet',
          common: 'Emirelezhioù Arab Unanet',
        },
        ces: {
          official: 'Spojené arabské emiráty',
          common: 'Arabské emiráty',
        },
        cym: {
          official: 'United Arab Emirates',
          common: 'United Arab Emirates',
        },
        deu: {
          official: 'Vereinigte Arabische Emirate',
          common: 'Vereinigte Arabische Emirate',
        },
        est: {
          official: 'Araabia Ühendemiraadid',
          common: 'Araabia Ühendemiraadid',
        },
        fin: {
          official: 'Yhdistyneet arabiemiirikunnat',
          common: 'Arabiemiraatit',
        },
        fra: {
          official: 'Émirats arabes unis',
          common: 'Émirats arabes unis',
        },
        hrv: {
          official: 'Ujedinjeni Arapski Emirati',
          common: 'Arapski Emirati',
        },
        hun: {
          official: 'Egyesült Arab Emírségek',
          common: 'Egyesült Arab Emírségek',
        },
        ita: {
          official: 'Emirati Arabi Uniti',
          common: 'Emirati Arabi Uniti',
        },
        jpn: { official: 'アラブ首長国連邦', common: 'アラブ首長国連邦' },
        kor: { official: '아랍 토후국 연방', common: '아랍에미리트' },
        nld: {
          official: 'Verenigde Arabische Emiraten',
          common: 'Verenigde Arabische Emiraten',
        },
        per: { official: 'امارات متحده عربی', common: 'امارات' },
        pol: {
          official: 'Zjednoczone Emiraty Arabskie',
          common: 'Emiraty Arabskie',
        },
        por: {
          official: 'Emirados Árabes Unidos',
          common: 'Emirados Árabes Unidos',
        },
        rus: {
          official: 'Объединенные Арабские Эмираты',
          common: 'Объединённые Арабские Эмираты',
        },
        slk: {
          official: 'Spojené arabské emiráty',
          common: 'Arabské emiráty',
        },
        spa: {
          official: 'Emiratos Árabes Unidos',
          common: 'Emiratos Árabes Unidos',
        },
        srp: {
          official: 'Уједињени Арапски Емирати',
          common: 'Уједињени Арапски Емирати',
        },
        swe: {
          official: 'Förenade Arabemiraten',
          common: 'Förenade Arabemiraten',
        },
        tur: {
          official: 'Birleşik Arap Emirlikleri',
          common: 'Birleşik Arap Emirlikleri',
        },
        urd: { official: 'متحدہ عرب امارات', common: 'متحدہ عرب امارات' },
        zho: { official: '阿拉伯联合酋长国', common: '阿拉伯联合酋长国' },
      },
      latlng: [24.0, 54.0],
      landlocked: false,
      borders: ['OMN', 'SAU'],
      area: 83600.0,
      demonyms: {
        eng: { f: 'Emirati', m: 'Emirati' },
        fra: { f: 'Emirienne', m: 'Emirien' },
      },
      flag: '\uD83C\uDDE6\uD83C\uDDEA',
      maps: {
        googleMaps: 'https://goo.gl/maps/AZZTDA6GzVAnKMVd8',
        openStreetMaps: 'https://www.openstreetmap.org/relation/307763',
      },
      population: 9890400,
      gini: { '2018': 26.0 },
      fifa: 'UAE',
      car: { signs: ['UAE'], side: 'right' },
      timezones: ['UTC+04:00'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/ae.png',
        svg: 'https://flagcdn.com/ae.svg',
        alt: 'The flag of United Arab Emirates features a red vertical band on its hoist side that takes up about one-fourth the width of the field and three equal horizontal bands of green, white and black adjoining the vertical band.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ae.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ae.svg',
      },
      startOfWeek: 'sunday',
      capitalInfo: { latlng: [24.47, 54.37] },
    },
    {
      name: {
        common: 'Ukraine',
        official: 'Ukraine',
        nativeName: { ukr: { official: 'Україна', common: 'Україна' } },
      },
      tld: ['.ua', '.укр'],
      cca2: 'UA',
      ccn3: '804',
      cca3: 'UKR',
      cioc: 'UKR',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { UAH: { name: 'Ukrainian hryvnia', symbol: '₴' } },
      idd: { root: '+3', suffixes: ['80'] },
      capital: ['Kyiv'],
      altSpellings: ['UA', 'Ukrayina'],
      region: 'Europe',
      subregion: 'Eastern Europe',
      languages: { ukr: 'Ukrainian' },
      translations: {
        ara: { official: 'أوكرانيا', common: 'أوكرانيا' },
        bre: { official: 'Ukraina', common: 'Ukraina' },
        ces: { official: 'Ukrajina', common: 'Ukrajina' },
        cym: { official: 'Ukraine', common: 'Ukraine' },
        deu: { official: 'Ukraine', common: 'Ukraine' },
        est: { official: 'Ukraina', common: 'Ukraina' },
        fin: { official: 'Ukraina', common: 'Ukraina' },
        fra: { official: 'Ukraine', common: 'Ukraine' },
        hrv: { official: 'Ukrajina', common: 'Ukrajina' },
        hun: { official: 'Ukrajna', common: 'Ukrajna' },
        ita: { official: 'Ucraina', common: 'Ucraina' },
        jpn: { official: 'ウクライナ', common: 'ウクライナ' },
        kor: { official: '우크라이나', common: '우크라이나' },
        nld: { official: 'Oekraïne', common: 'Oekraïne' },
        per: { official: 'اوکراین', common: 'اوکراین' },
        pol: { official: 'Ukraina', common: 'Ukraina' },
        por: { official: 'Ucrânia', common: 'Ucrânia' },
        rus: { official: 'Украина', common: 'Украина' },
        slk: { official: 'Ukrajina', common: 'Ukrajina' },
        spa: { official: 'Ucrania', common: 'Ucrania' },
        srp: { official: 'Украјина', common: 'Украјина' },
        swe: { official: 'Ukraina', common: 'Ukraina' },
        tur: { official: 'Ukrayna', common: 'Ukrayna' },
        urd: { official: 'یوکرین', common: 'یوکرین' },
        zho: { official: '乌克兰', common: '乌克兰' },
      },
      latlng: [49.0, 32.0],
      landlocked: false,
      borders: ['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK'],
      area: 603500.0,
      demonyms: {
        eng: { f: 'Ukrainian', m: 'Ukrainian' },
        fra: { f: 'Ukrainienne', m: 'Ukrainien' },
      },
      flag: '\uD83C\uDDFA\uD83C\uDDE6',
      maps: {
        googleMaps: 'https://goo.gl/maps/DvgJMiPJ7aozKFZv7',
        openStreetMaps: 'https://www.openstreetmap.org/relation/60199',
      },
      population: 44134693,
      gini: { '2019': 26.6 },
      fifa: 'UKR',
      car: { signs: ['UA'], side: 'right' },
      timezones: ['UTC+02:00'],
      continents: ['Europe'],
      flags: {
        png: 'https://flagcdn.com/w320/ua.png',
        svg: 'https://flagcdn.com/ua.svg',
        alt: 'The flag of Ukraine is composed of two equal horizontal bands of blue and yellow.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ua.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ua.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [50.43, 30.52] },
      postalCode: { format: '#####', regex: '^(\\d{5})$' },
    },
    {
      name: {
        common: 'Guinea-Bissau',
        official: 'Republic of Guinea-Bissau',
        nativeName: {
          por: {
            official: 'República da Guiné-Bissau',
            common: 'Guiné-Bissau',
          },
          pov: {
            official: 'República da Guiné-Bissau',
            common: 'Guiné-Bissau',
          },
        },
      },
      tld: ['.gw'],
      cca2: 'GW',
      ccn3: '624',
      cca3: 'GNB',
      cioc: 'GBS',
      independent: true,
      status: 'officially-assigned',
      unMember: false,
      currencies: {
        XOF: { name: 'West African CFA franc', symbol: 'Fr' },
      },
      idd: { root: '+2', suffixes: ['45'] },
      capital: ['Bissau'],
      altSpellings: ['GW', 'Republic of Guinea-Bissau', 'República da Guiné-Bissau'],
      region: 'Africa',
      subregion: 'Western Africa',
      languages: { por: 'Portuguese', pov: 'Upper Guinea Creole' },
      translations: {
        ara: { official: 'جمهورية غينيا بيساو', common: 'غينيا بيساو' },
        bre: { official: 'Republik Ginea-Bissau', common: 'Ginea-Bissau' },
        ces: {
          official: 'Republika Guinea-Bissau',
          common: 'Guinea-Bissau',
        },
        cym: {
          official: 'Republic of Guinea-Bissau',
          common: 'Guinea-Bissau',
        },
        deu: {
          official: 'Republik Guinea-Bissau',
          common: 'Guinea-Bissau',
        },
        est: {
          official: 'Guinea-Bissau Vabariik',
          common: 'Guinea-Bissau',
        },
        fin: {
          official: 'Guinea-Bissaun tasavalta',
          common: 'Guinea-Bissau',
        },
        fra: {
          official: 'République de Guinée-Bissau',
          common: 'Guinée-Bissau',
        },
        hrv: {
          official: 'Republika Gvineja Bisau',
          common: 'Gvineja Bisau',
        },
        hun: {
          official: 'Bissau-Guineai Köztársaság',
          common: 'Bissau-Guinea',
        },
        ita: {
          official: 'Repubblica di Guinea-Bissau',
          common: 'Guinea-Bissau',
        },
        jpn: { official: 'ギニアビサウ共和国', common: 'ギニアビサウ' },
        kor: { official: '기니비사우 공화국', common: '기니비사우' },
        nld: {
          official: 'Republiek Guinee-Bissau',
          common: 'Guinee-Bissau',
        },
        per: { official: 'جمهوری گینه بیسائو', common: 'گینه بیسائو' },
        pol: {
          official: 'Republika Gwinei Bissau',
          common: 'Gwinea Bissau',
        },
        por: {
          official: 'República da Guiné-Bissau',
          common: 'Guiné-Bissau',
        },
        rus: {
          official: 'Республика Гвинея -Бисау',
          common: 'Гвинея-Бисау',
        },
        slk: {
          official: 'Guinejsko-bissauská republika',
          common: 'Guinea-Bissau',
        },
        spa: {
          official: 'República de Guinea-Bissau',
          common: 'Guinea-Bisáu',
        },
        srp: {
          official: 'Република Гвинеја Бисао',
          common: 'Гвинеја Бисао',
        },
        swe: {
          official: 'Republiken Guinea-Bissau',
          common: 'Guinea-Bissau',
        },
        tur: { official: 'Gine-Bissau Cumhuriyeti', common: 'Gine-Bissau' },
        urd: { official: 'جمہوریہ گنی بساؤ', common: 'گنی بساؤ' },
        zho: { official: '几内亚比绍共和国', common: '几内亚比绍' },
      },
      latlng: [12.0, -15.0],
      landlocked: false,
      borders: ['GIN', 'SEN'],
      area: 36125.0,
      demonyms: {
        eng: { f: 'Guinea-Bissauan', m: 'Guinea-Bissauan' },
        fra: { f: 'Bissau-Guinéenne', m: 'Bissau-Guinéen' },
      },
      flag: '\uD83C\uDDEC\uD83C\uDDFC',
      maps: {
        googleMaps: 'https://goo.gl/maps/5Wyaz17miUc1zLc67',
        openStreetMaps: 'https://www.openstreetmap.org/relation/192776',
      },
      population: 1967998,
      gini: { '2010': 50.7 },
      fifa: 'GNB',
      car: { signs: ['RGB'], side: 'right' },
      timezones: ['UTC'],
      continents: ['Africa'],
      flags: {
        png: 'https://flagcdn.com/w320/gw.png',
        svg: 'https://flagcdn.com/gw.svg',
        alt: 'The flag of Guinea-Bissau features a red vertical band on its hoist side that takes up about two-fifth the width of the field, and two equal horizontal bands of yellow and green adjoining the vertical band. A five-pointed black star is centered in the vertical band.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/gw.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/gw.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [11.85, -15.58] },
      postalCode: { format: '####', regex: '^(\\d{4})$' },
    },
    {
      name: {
        common: 'Palestine',
        official: 'State of Palestine',
        nativeName: { ara: { official: 'دولة فلسطين', common: 'فلسطين' } },
      },
      tld: ['.ps', 'فلسطين.'],
      cca2: 'PS',
      ccn3: '275',
      cca3: 'PSE',
      cioc: 'PLE',
      independent: false,
      status: 'officially-assigned',
      unMember: false,
      currencies: {
        EGP: { name: 'Egyptian pound', symbol: 'E£' },
        ILS: { name: 'Israeli new shekel', symbol: '₪' },
        JOD: { name: 'Jordanian dinar', symbol: 'JD' },
      },
      idd: { root: '+9', suffixes: ['70'] },
      capital: ['Ramallah', 'Jerusalem'],
      altSpellings: ['PS', 'Palestine, State of', 'State of Palestine', 'Dawlat Filasṭin'],
      region: 'Asia',
      subregion: 'Western Asia',
      languages: { ara: 'Arabic' },
      translations: {
        ara: { official: 'دولة فلسطين', common: 'فلسطين' },
        bre: { official: 'Stad Palestina', common: 'Palestina' },
        ces: { official: 'Stát Palestina', common: 'Palestina' },
        cym: { official: 'State of Palestine', common: 'Palestine' },
        deu: { official: 'Staat Palästina', common: 'Palästina' },
        est: { official: 'Palestiina Riik', common: 'Palestiina' },
        fin: { official: 'Palestiinan valtio', common: 'Palestiina' },
        fra: { official: 'État de Palestine', common: 'Palestine' },
        hrv: { official: 'State of Palestine', common: 'Palestina' },
        hun: { official: 'Palesztin Autonómia', common: 'Palesztina' },
        ita: { official: 'Stato di Palestina', common: 'Palestina' },
        jpn: { official: 'パレスチナ自治政府', common: 'パレスチナ' },
        kor: { official: '팔레스타인국', common: '팔레스타인' },
        nld: {
          official: 'Staat Palestina',
          common: 'Palestijnse gebieden',
        },
        per: { official: 'دولت فلسطین', common: 'فلسطین' },
        pol: { official: 'Państwo Palestyna', common: 'Palestyna' },
        por: { official: 'Estado da Palestina', common: 'Palestina' },
        rus: { official: 'Государство Палестина', common: 'Палестина' },
        slk: { official: 'Palestínsky štát', common: 'Palestína' },
        spa: { official: 'Estado de Palestina', common: 'Palestina' },
        srp: { official: 'Држава Палестина', common: 'Палестина' },
        swe: { official: 'Palestina', common: 'Palestina' },
        tur: { official: 'Filistin Devleti', common: 'Filistin' },
        urd: { official: 'ریاستِ فلسطین', common: 'فلسطین' },
        zho: { official: '巴勒斯坦国', common: '巴勒斯坦' },
      },
      latlng: [31.9, 35.2],
      landlocked: false,
      borders: ['ISR', 'EGY', 'JOR'],
      area: 6220.0,
      demonyms: {
        eng: { f: 'Palestinian', m: 'Palestinian' },
        fra: { f: 'Palestinienne', m: 'Palestinien' },
      },
      flag: '\uD83C\uDDF5\uD83C\uDDF8',
      maps: {
        googleMaps: 'https://goo.gl/maps/QvTbkRdmdWEoYAmt5',
        openStreetMaps: 'https://www.openstreetmap.org/relation/1703814',
      },
      population: 4803269,
      gini: { '2016': 33.7 },
      fifa: 'PLE',
      car: { signs: ['PS'], side: 'right' },
      timezones: ['UTC+02:00'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/ps.png',
        svg: 'https://flagcdn.com/ps.svg',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ps.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ps.svg',
      },
      startOfWeek: 'sunday',
      capitalInfo: { latlng: [31.9, 35.2] },
    },
    {
      name: {
        common: 'Nepal',
        official: 'Federal Democratic Republic of Nepal',
        nativeName: {
          nep: {
            official: 'नेपाल संघीय लोकतान्त्रिक गणतन्त्र',
            common: 'नेपाल',
          },
        },
      },
      tld: ['.np'],
      cca2: 'NP',
      ccn3: '524',
      cca3: 'NPL',
      cioc: 'NEP',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { NPR: { name: 'Nepalese rupee', symbol: '₨' } },
      idd: { root: '+9', suffixes: ['77'] },
      capital: ['Kathmandu'],
      altSpellings: ['NP', 'Federal Democratic Republic of Nepal', 'Loktāntrik Ganatantra Nepāl'],
      region: 'Asia',
      subregion: 'Southern Asia',
      languages: { nep: 'Nepali' },
      translations: {
        ara: {
          official: 'جمهورية نيبال الديمقراطية الاتحادية',
          common: 'نيبال',
        },
        bre: {
          official: 'Republik Demokratel Kevreadel Nepal',
          common: 'Nepal',
        },
        ces: {
          official: 'Federativní demokratická republika Nepál',
          common: 'Nepál',
        },
        cym: {
          official: 'Federal Democratic Republic of Nepal',
          common: 'Nepal',
        },
        deu: {
          official: 'Demokratische Bundesrepublik Nepal',
          common: 'Nepal',
        },
        est: {
          official: 'Nepali Demokraatlik Liitvabariik',
          common: 'Nepal',
        },
        fin: {
          official: 'Nepalin demokraattinen liittotasavalta',
          common: 'Nepal',
        },
        fra: { official: 'République du Népal', common: 'Népal' },
        hrv: {
          official: 'Savezna Demokratska Republika Nepal',
          common: 'Nepal',
        },
        hun: {
          official: 'Nepáli Szövetségi Demokratikus Köztársaság',
          common: 'Nepál',
        },
        ita: {
          official: 'Repubblica federale democratica del Nepal',
          common: 'Nepal',
        },
        jpn: { official: 'ネパール連邦民主共和国', common: 'ネパール' },
        kor: { official: '네팔 연방 민주 공화국', common: '네팔' },
        nld: {
          official: 'Federale Democratische Republiek Nepal',
          common: 'Nepal',
        },
        per: { official: 'جمهوری فدرال دموکراتیک نپال', common: 'نپال' },
        pol: {
          official: 'Federalna Demokratyczna Republika Nepalu',
          common: 'Nepal',
        },
        por: {
          official: 'República Democrática Federal do Nepal',
          common: 'Nepal',
        },
        rus: {
          official: 'Федеративная Демократическая Республика Непал',
          common: 'Непал',
        },
        slk: {
          official: 'Nepálska federatívna demokratická republika',
          common: 'Nepál',
        },
        spa: {
          official: 'República Democrática Federal de Nepal',
          common: 'Nepal',
        },
        srp: {
          official: 'Савезна Демократска Република Непал',
          common: 'Непал',
        },
        swe: {
          official: 'Demokratiska förbundsrepubliken Nepal',
          common: 'Nepal',
        },
        tur: {
          official: 'Nepal Federal Demokratik Cumhuriyeti',
          common: 'Nepal',
        },
        urd: { official: 'وفاقی جمہوری جمہوریہ نیپال', common: 'نیپال' },
        zho: { official: '尼泊尔联邦民主共和国', common: '尼泊尔' },
      },
      latlng: [28.0, 84.0],
      landlocked: true,
      borders: ['CHN', 'IND'],
      area: 147181.0,
      demonyms: {
        eng: { f: 'Nepalese', m: 'Nepalese' },
        fra: { f: 'Népalaise', m: 'Népalais' },
      },
      flag: '\uD83C\uDDF3\uD83C\uDDF5',
      maps: {
        googleMaps: 'https://goo.gl/maps/UMj2zpbQp7B5c3yT7',
        openStreetMaps: 'https://www.openstreetmap.org/relation/184633',
      },
      population: 29136808,
      gini: { '2010': 32.8 },
      fifa: 'NEP',
      car: { signs: ['NEP'], side: 'left' },
      timezones: ['UTC+05:45'],
      continents: ['Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/np.png',
        svg: 'https://flagcdn.com/np.svg',
        alt: "The flag of Nepal is the world's only non-quadrilateral flag of a sovereign country. It takes the shape of two adjoining right-angled triangles and has a crimson red field with deep blue edges. Within the smaller upper triangle is an emblem of the upper half of a white sun resting on an upward facing white crescent. The lower triangle bears a white sun with twelve rays.",
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/np.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/np.svg',
      },
      startOfWeek: 'sunday',
      capitalInfo: { latlng: [27.72, 85.32] },
      postalCode: { format: '#####', regex: '^(\\d{5})$' },
    },
    {
      name: {
        common: 'South Africa',
        official: 'Republic of South Africa',
        nativeName: {
          afr: {
            official: 'Republiek van Suid-Afrika',
            common: 'South Africa',
          },
          eng: {
            official: 'Republic of South Africa',
            common: 'South Africa',
          },
          nbl: {
            official: 'IRiphabliki yeSewula Afrika',
            common: 'Sewula Afrika',
          },
          nso: {
            official: 'Rephaboliki ya Afrika-Borwa ',
            common: 'Afrika-Borwa',
          },
          sot: {
            official: 'Rephaboliki ya Afrika Borwa',
            common: 'Afrika Borwa',
          },
          ssw: {
            official: 'IRiphabhulikhi yeNingizimu Afrika',
            common: 'Ningizimu Afrika',
          },
          tsn: {
            official: 'Rephaboliki ya Aforika Borwa',
            common: 'Aforika Borwa',
          },
          tso: {
            official: 'Riphabliki ra Afrika Dzonga',
            common: 'Afrika Dzonga',
          },
          ven: {
            official: 'Riphabuḽiki ya Afurika Tshipembe',
            common: 'Afurika Tshipembe',
          },
          xho: {
            official: 'IRiphabliki yaseMzantsi Afrika',
            common: 'Mzantsi Afrika',
          },
          zul: {
            official: 'IRiphabliki yaseNingizimu Afrika',
            common: 'Ningizimu Afrika',
          },
        },
      },
      tld: ['.za'],
      cca2: 'ZA',
      ccn3: '710',
      cca3: 'ZAF',
      cioc: 'RSA',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { ZAR: { name: 'South African rand', symbol: 'R' } },
      idd: { root: '+2', suffixes: ['7'] },
      capital: ['Pretoria', 'Bloemfontein', 'Cape Town'],
      altSpellings: ['ZA', 'RSA', 'Suid-Afrika', 'Republic of South Africa'],
      region: 'Africa',
      subregion: 'Southern Africa',
      languages: {
        afr: 'Afrikaans',
        eng: 'English',
        nbl: 'Southern Ndebele',
        nso: 'Northern Sotho',
        sot: 'Southern Sotho',
        ssw: 'Swazi',
        tsn: 'Tswana',
        tso: 'Tsonga',
        ven: 'Venda',
        xho: 'Xhosa',
        zul: 'Zulu',
      },
      translations: {
        ara: { official: 'جمهورية جنوب أفريقيا', common: 'جنوب أفريقيا' },
        bre: { official: 'Republik Suafrika', common: 'Suafrika' },
        ces: {
          official: 'Jihoafrická republika',
          common: 'Jihoafrická republika',
        },
        cym: {
          official: 'Republic of South Africa',
          common: 'South Africa',
        },
        deu: { official: 'Republik Südafrika', common: 'Südafrika' },
        est: {
          official: 'Lõuna-Aafrika Vabariik',
          common: 'Lõuna-Aafrika Vabariik',
        },
        fin: {
          official: 'Etelä-Afrikan tasavalta',
          common: 'Etelä-Afrikka',
        },
        fra: {
          official: "République d'Afrique du Sud",
          common: 'Afrique du Sud',
        },
        hrv: { official: 'Južnoafrička Republika', common: 'Južna Afrika' },
        hun: {
          official: 'Dél-afrikai Köztársaság',
          common: 'Dél-afrikai Köztársaság',
        },
        ita: {
          official: 'Repubblica del Sud Africa',
          common: 'Sud Africa',
        },
        jpn: { official: '南アフリカ共和国', common: '南アフリカ' },
        kor: { official: '남아프리카 공화국', common: '남아프리카' },
        nld: { official: 'Republiek Zuid-Afrika', common: 'Zuid-Afrika' },
        per: { official: 'جمهوری آفریقای جنوبی', common: 'آفریقای جنوبی' },
        pol: {
          official: 'Republika Południowej Afryki',
          common: 'Południowa Afryka',
        },
        por: {
          official: 'República da África do Sul',
          common: 'África do Sul',
        },
        rus: {
          official: 'Южно-Африканская Республика',
          common: 'Южная Африка',
        },
        slk: { official: 'Juhoafrická republika', common: 'Južná Afrika' },
        spa: { official: 'República de Sudáfrica', common: 'Sudáfrica' },
        srp: {
          official: 'Република Јужна Африка',
          common: 'Јужноафричка Република',
        },
        swe: { official: 'Republiken Sydafrika', common: 'Sydafrika' },
        tur: {
          official: 'Güney Afrika Cumhuriyeti',
          common: 'Güney Afrika',
        },
        urd: { official: 'جمہوریہ جنوبی افریقا', common: 'جنوبی افریقا' },
        zho: { official: '南非共和国', common: '南非' },
      },
      latlng: [-29.0, 24.0],
      landlocked: false,
      borders: ['BWA', 'LSO', 'MOZ', 'NAM', 'SWZ', 'ZWE'],
      area: 1221037.0,
      demonyms: {
        eng: { f: 'South African', m: 'South African' },
        fra: { f: 'Sud-africaine', m: 'Sud-africain' },
      },
      flag: '\uD83C\uDDFF\uD83C\uDDE6',
      maps: {
        googleMaps: 'https://goo.gl/maps/CLCZ1R8Uz1KpYhRv6',
        openStreetMaps: 'https://www.openstreetmap.org/relation/87565',
      },
      population: 59308690,
      gini: { '2014': 63.0 },
      fifa: 'RSA',
      car: { signs: ['ZA'], side: 'left' },
      timezones: ['UTC+02:00'],
      continents: ['Africa'],
      flags: {
        png: 'https://flagcdn.com/w320/za.png',
        svg: 'https://flagcdn.com/za.svg',
        alt: 'The flag of South Africa is composed of two equal horizontal bands of red and blue, with a yellow-edged black isosceles triangle superimposed on the hoist side of the field. This triangle has its base centered on the hoist end, spans about two-fifth the width and two-third the height of the field, and is enclosed on its sides by the arms of a white-edged green horizontally oriented Y-shaped band which extends along the boundary of the red and blue bands to the fly end of the field.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/za.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/za.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [-25.7, 28.22] },
      postalCode: { format: '####', regex: '^(\\d{4})$' },
    },
    {
      name: {
        common: 'Russia',
        official: 'Russian Federation',
        nativeName: {
          rus: { official: 'Российская Федерация', common: 'Россия' },
        },
      },
      tld: ['.ru', '.su', '.рф'],
      cca2: 'RU',
      ccn3: '643',
      cca3: 'RUS',
      cioc: 'RUS',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { RUB: { name: 'Russian ruble', symbol: '₽' } },
      idd: { root: '+7', suffixes: ['3', '4', '5', '8', '9'] },
      capital: ['Moscow'],
      altSpellings: ['RU', 'Russian Federation', 'Российская Федерация'],
      region: 'Europe',
      subregion: 'Eastern Europe',
      languages: { rus: 'Russian' },
      translations: {
        ara: { official: 'روسيا الاتحادية', common: 'روسيا' },
        bre: { official: 'Kevread Rusia', common: 'Rusia' },
        ces: { official: 'Ruská federace', common: 'Rusko' },
        cym: { official: 'Russian Federation', common: 'Russia' },
        deu: { official: 'Russische Föderation', common: 'Russland' },
        est: { official: 'Venemaa Föderatsioon', common: 'Venemaa' },
        fin: { official: 'Venäjän federaatio', common: 'Venäjä' },
        fra: { official: 'Fédération de Russie', common: 'Russie' },
        hrv: { official: 'Ruska Federacija', common: 'Rusija' },
        hun: { official: 'Oroszországi Föderáció', common: 'Oroszország' },
        ita: { official: 'Federazione russa', common: 'Russia' },
        jpn: { official: 'ロシア連邦', common: 'ロシア連邦' },
        kor: { official: '러시아 연방', common: '러시아' },
        nld: { official: 'Russische Federatie', common: 'Rusland' },
        per: { official: 'فدراسیون روسیه', common: 'روسیه' },
        pol: { official: 'Federacja Rosyjska', common: 'Rosja' },
        por: { official: 'Federação Russa', common: 'Rússia' },
        rus: { official: 'Российская Федерация', common: 'Россия' },
        slk: { official: 'Ruská federácia', common: 'Rusko' },
        spa: { official: 'Federación de Rusia', common: 'Rusia' },
        srp: { official: 'Руска Федерација', common: 'Русија' },
        swe: { official: 'Ryska federationen', common: 'Ryssland' },
        tur: { official: 'Rusya Federasyonu', common: 'Rusya' },
        urd: { official: 'روسی وفاق', common: 'روس' },
        zho: { official: '俄罗斯联邦', common: '俄罗斯' },
      },
      latlng: [60.0, 100.0],
      landlocked: false,
      borders: ['AZE', 'BLR', 'CHN', 'EST', 'FIN', 'GEO', 'KAZ', 'PRK', 'LVA', 'LTU', 'MNG', 'NOR', 'POL', 'UKR'],
      area: 1.7098242e7,
      demonyms: {
        eng: { f: 'Russian', m: 'Russian' },
        fra: { f: 'Russe', m: 'Russe' },
      },
      flag: '\uD83C\uDDF7\uD83C\uDDFA',
      maps: {
        googleMaps: 'https://goo.gl/maps/4F4PpDhGJgVvLby57',
        openStreetMaps: 'https://www.openstreetmap.org/relation/60189#map=3/65.15/105.29',
      },
      population: 144104080,
      gini: { '2018': 37.5 },
      fifa: 'RUS',
      car: { signs: ['RUS'], side: 'right' },
      timezones: [
        'UTC+03:00',
        'UTC+04:00',
        'UTC+06:00',
        'UTC+07:00',
        'UTC+08:00',
        'UTC+09:00',
        'UTC+10:00',
        'UTC+11:00',
        'UTC+12:00',
      ],
      continents: ['Europe', 'Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/ru.png',
        svg: 'https://flagcdn.com/ru.svg',
        alt: 'The flag of Russia is composed of three equal horizontal bands of white, blue and red.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/ru.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/ru.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [55.75, 37.6] },
      postalCode: { format: '######', regex: '^(\\d{6})$' },
    },
    {
      name: {
        common: 'Turkey',
        official: 'Republic of Turkey',
        nativeName: {
          tur: { official: 'Türkiye Cumhuriyeti', common: 'Türkiye' },
        },
      },
      tld: ['.tr'],
      cca2: 'TR',
      ccn3: '792',
      cca3: 'TUR',
      cioc: 'TUR',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { TRY: { name: 'Turkish lira', symbol: '₺' } },
      idd: { root: '+9', suffixes: ['0'] },
      capital: ['Ankara'],
      altSpellings: ['TR', 'Turkiye', 'Republic of Turkey', 'Türkiye Cumhuriyeti'],
      region: 'Asia',
      subregion: 'Western Asia',
      languages: { tur: 'Turkish' },
      translations: {
        ara: { official: 'الجمهورية التركية', common: 'تركيا' },
        bre: { official: 'Republik Turkia', common: 'Turkia' },
        ces: { official: 'Turecká republika', common: 'Turecko' },
        cym: { official: 'Republic of Turkey', common: 'Turkey' },
        deu: { official: 'Republik Türkei', common: 'Türkei' },
        est: { official: 'Türgi Vabariik', common: 'Türgi' },
        fin: { official: 'Turkin tasavalta', common: 'Turkki' },
        fra: { official: 'République de Turquie', common: 'Turquie' },
        hrv: { official: 'Republika Turska', common: 'Turska' },
        hun: { official: 'Török Köztársaság', common: 'Törökország' },
        ita: { official: 'Repubblica di Turchia', common: 'Turchia' },
        jpn: { official: 'トルコ共和国', common: 'トルコ' },
        kor: { official: '터키 공화국', common: '터키' },
        nld: { official: 'Republiek Turkije', common: 'Turkije' },
        per: { official: 'جمهوری ترکیه', common: 'ترکیه' },
        pol: { official: 'Republika Turcji', common: 'Turcja' },
        por: { official: 'República da Turquia', common: 'Turquia' },
        rus: { official: 'Республика Турции', common: 'Турция' },
        slk: { official: 'Turecká republika', common: 'Turecko' },
        spa: { official: 'República de Turquía', common: 'Turquía' },
        srp: { official: 'Турска Република', common: 'Турска' },
        swe: { official: 'Republiken Turkiet', common: 'Turkiet' },
        tur: { official: 'Türkiye Cumhuriyeti', common: 'Türkiye' },
        urd: { official: 'جمہوریہ ترکی', common: 'ترکی' },
        zho: { official: '土耳其共和国', common: '土耳其' },
      },
      latlng: [39.0, 35.0],
      landlocked: false,
      borders: ['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IRQ', 'SYR'],
      area: 783562.0,
      demonyms: {
        eng: { f: 'Turkish', m: 'Turkish' },
        fra: { f: 'Turque', m: 'Turc' },
      },
      flag: '\uD83C\uDDF9\uD83C\uDDF7',
      maps: {
        googleMaps: 'https://goo.gl/maps/dXFFraiUDfcB6Quk6',
        openStreetMaps: 'https://www.openstreetmap.org/relation/174737',
      },
      population: 84339067,
      gini: { '2019': 41.9 },
      fifa: 'TUR',
      car: { signs: ['TR'], side: 'right' },
      timezones: ['UTC+03:00'],
      continents: ['Europe', 'Asia'],
      flags: {
        png: 'https://flagcdn.com/w320/tr.png',
        svg: 'https://flagcdn.com/tr.svg',
        alt: 'The flag of Turkey has a red field bearing a large fly-side facing white crescent and a smaller five-pointed white star placed just outside the crescent opening. The white crescent and star are offset slightly towards the hoist side of center.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/tr.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/tr.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [39.93, 32.87] },
      postalCode: { format: '#####', regex: '^(\\d{5})$' },
    },
    {
      name: {
        common: 'Czechia',
        official: 'Czech Republic',
        nativeName: {
          ces: { official: 'Česká republika', common: 'Česko' },
          slk: { official: 'Česká republika', common: 'Česko' },
        },
      },
      tld: ['.cz'],
      cca2: 'CZ',
      ccn3: '203',
      cca3: 'CZE',
      cioc: 'CZE',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { CZK: { name: 'Czech koruna', symbol: 'Kč' } },
      idd: { root: '+4', suffixes: ['20'] },
      capital: ['Prague'],
      altSpellings: ['CZ', 'Česká republika', 'Česko'],
      region: 'Europe',
      subregion: 'Central Europe',
      languages: { ces: 'Czech', slk: 'Slovak' },
      translations: {
        ara: { official: 'جمهورية التشيك', common: 'التشيك' },
        bre: { official: 'Republik Tchek', common: 'Tchekia' },
        ces: { official: 'Česká republika', common: 'Česko' },
        cym: {
          official: 'Y Weriniaeth Tsiec',
          common: 'Y Weriniaeth Tsiec',
        },
        deu: { official: 'Tschechische Republik', common: 'Tschechien' },
        est: { official: 'Tšehhi Vabariik', common: 'Tšehhi' },
        fin: { official: 'Tšekin tasavalta', common: 'Tšekki' },
        fra: { official: 'République tchèque', common: 'Tchéquie' },
        hrv: { official: 'Češka', common: 'Češka' },
        hun: { official: 'Cseh Köztársaság', common: 'Csehország' },
        ita: { official: 'Repubblica Ceca', common: 'Cechia' },
        jpn: { official: 'チェコ共和国', common: 'チェコ' },
        kor: { official: '체코', common: '체코' },
        nld: { official: 'Tsjechische Republiek', common: 'Tsjechië' },
        per: { official: 'جمهوری چک', common: 'جمهوری چک' },
        pol: { official: 'Republika Czeska', common: 'Czechy' },
        por: { official: 'República Checa', common: 'Chéquia' },
        rus: { official: 'Чешская Республика', common: 'Чехия' },
        slk: { official: 'Česká republika', common: 'Česko' },
        spa: { official: 'República Checa', common: 'Chequia' },
        srp: { official: 'Чешка Република', common: 'Чешка' },
        swe: { official: 'Republiken Tjeckien', common: 'Tjeckien' },
        tur: { official: 'Çek Cumhuriyeti', common: 'Çekya' },
        urd: { official: 'چيک جمہوريہ', common: 'چيک' },
        zho: { official: '捷克共和国', common: '捷克' },
      },
      latlng: [49.75, 15.5],
      landlocked: true,
      borders: ['AUT', 'DEU', 'POL', 'SVK'],
      area: 78865.0,
      demonyms: {
        eng: { f: 'Czech', m: 'Czech' },
        fra: { f: 'Tchèque', m: 'Tchèque' },
      },
      flag: '\uD83C\uDDE8\uD83C\uDDFF',
      maps: {
        googleMaps: 'https://goo.gl/maps/47dmgeXMZyhDHyQW8',
        openStreetMaps: 'https://www.openstreetmap.org/relation/51684',
      },
      population: 10698896,
      gini: { '2018': 25.0 },
      fifa: 'CZE',
      car: { signs: ['CZ'], side: 'right' },
      timezones: ['UTC+01:00'],
      continents: ['Europe'],
      flags: {
        png: 'https://flagcdn.com/w320/cz.png',
        svg: 'https://flagcdn.com/cz.svg',
        alt: 'The flag of Czechia is composed of two equal horizontal bands of white and red, with a blue isosceles triangle superimposed on the hoist side of the field. The triangle has its base on the hoist end and spans about two-fifth the width of the field.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/cz.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/cz.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [50.08, 14.47] },
      postalCode: { format: '### ##', regex: '^(\\d{5})$' },
    },
    {
      name: {
        common: 'Serbia',
        official: 'Republic of Serbia',
        nativeName: {
          srp: { official: 'Република Србија', common: 'Србија' },
        },
      },
      tld: ['.rs', '.срб'],
      cca2: 'RS',
      ccn3: '688',
      cca3: 'SRB',
      cioc: 'SRB',
      independent: true,
      status: 'officially-assigned',
      unMember: true,
      currencies: { RSD: { name: 'Serbian dinar', symbol: 'дин.' } },
      idd: { root: '+3', suffixes: ['81'] },
      capital: ['Belgrade'],
      altSpellings: ['RS', 'Srbija', 'Republic of Serbia', 'Република Србија', 'Republika Srbija'],
      region: 'Europe',
      subregion: 'Southeast Europe',
      languages: { srp: 'Serbian' },
      translations: {
        ara: { official: 'جمهورية صيربيا', common: 'صيربيا' },
        bre: { official: 'Republik Serbia', common: 'Serbia' },
        ces: { official: 'Srbská republika', common: 'Srbsko' },
        cym: { official: 'Republic of Serbia', common: 'Serbia' },
        deu: { official: 'Republik Serbien', common: 'Serbien' },
        est: { official: 'Serbia Vabariik', common: 'Serbia' },
        fin: { official: 'Serbian tasavalta', common: 'Serbia' },
        fra: { official: 'République de Serbie', common: 'Serbie' },
        hrv: { official: 'Republika Srbija', common: 'Srbija' },
        hun: { official: 'Szerb Köztársaság', common: 'Szerbia' },
        ita: { official: 'Repubblica di Serbia', common: 'Serbia' },
        jpn: { official: 'セルビア共和国', common: 'セルビア' },
        kor: { official: '세르비아 공화국', common: '세르비아' },
        nld: { official: 'Republiek Servië', common: 'Servië' },
        per: { official: 'جمهوری صربستان', common: 'صربستان' },
        pol: { official: 'Republika Serbii', common: 'Serbia' },
        por: { official: 'República da Sérvia', common: 'Sérvia' },
        rus: { official: 'Республика Сербия', common: 'Сербия' },
        slk: { official: 'Srbská republika', common: 'Srbsko' },
        spa: { official: 'República de Serbia', common: 'Serbia' },
        srp: { official: 'Република Србија', common: 'Србија' },
        swe: { official: 'Republiken Serbien', common: 'Serbien' },
        tur: { official: 'Sırbistan Cumhuriyeti', common: 'Sırbistan' },
        urd: { official: 'جمہوریہ سربیا', common: 'سربیا' },
        zho: { official: '塞尔维亚共和国', common: '塞尔维亚' },
      },
      latlng: [44.0, 21.0],
      landlocked: true,
      borders: ['BIH', 'BGR', 'HRV', 'HUN', 'UNK', 'MKD', 'MNE', 'ROU'],
      area: 88361.0,
      demonyms: {
        eng: { f: 'Serbian', m: 'Serbian' },
        fra: { f: 'Serbe', m: 'Serbe' },
      },
      flag: '\uD83C\uDDF7\uD83C\uDDF8',
      maps: {
        googleMaps: 'https://goo.gl/maps/2Aqof7aV2Naq8YEK8',
        openStreetMaps: 'https://www.openstreetmap.org/relation/1741311',
      },
      population: 6908224,
      gini: { '2017': 36.2 },
      fifa: 'SRB',
      car: { signs: ['SRB'], side: 'right' },
      timezones: ['UTC+01:00'],
      continents: ['Europe'],
      flags: {
        png: 'https://flagcdn.com/w320/rs.png',
        svg: 'https://flagcdn.com/rs.svg',
        alt: 'The flag of Serbia is composed of three equal horizontal bands of red, blue and white. The coat of arms of Serbia is superimposed at the center of the field slightly towards the hoist side.',
      },
      coatOfArms: {
        png: 'https://mainfacts.com/media/images/coats_of_arms/rs.png',
        svg: 'https://mainfacts.com/media/images/coats_of_arms/rs.svg',
      },
      startOfWeek: 'monday',
      capitalInfo: { latlng: [44.83, 20.5] },
      postalCode: { format: '######', regex: '^(\\d{6})$' },
    },
  ]);
}
